module.exports = {
    purge: [
        "./static/src/html/partials/viewer_page.pug",
        "./static/src/html/partials/gc_page.pug",
        "./static/src/html/about_en.pug",
        "./static/src/html/about_kk.pug",
        "./static/src/html/about_ru.pug",
        "./static/src/html/declension_ru.pug",
        "./static/src/html/explanation_en.pug",
        "./static/src/html/explanation_ru.pug",
        "./static/src/html/gc_create_ru.pug",
        "./static/src/html/gc_search_ru.pug",
        "./static/src/html/viewer.pug",
        "./static/src/html/viewer_en.pug",
        "./static/src/html/viewer_kk.pug",
        "./static/src/javascripts/components/close_button.jsx",
        "./static/src/javascripts/components/declension_app.jsx",
        "./static/src/javascripts/components/detector_app.jsx",
        "./static/src/javascripts/components/edit_button.jsx",
        "./static/src/javascripts/components/explanation_app.jsx",
        "./static/src/javascripts/components/gc_create_app.jsx",
        "./static/src/javascripts/components/gc_reviews_app.jsx",
        "./static/src/javascripts/components/gc_search_app.jsx",
        "./static/src/javascripts/components/gc_word_create.jsx",
        "./static/src/javascripts/components/gc_word_selection.jsx",
        "./static/src/javascripts/components/gc_word_start.jsx",
        "./static/src/javascripts/components/gym_app.jsx",
        "./static/src/javascripts/components/gym_cheatsheet.jsx",
        "./static/src/javascripts/components/gym_exercise.jsx",
        "./static/src/javascripts/components/gym_start.jsx",
        "./static/src/javascripts/components/keyboard_input.jsx",
        "./static/src/javascripts/components/keyboard.jsx",
        "./static/src/javascripts/components/viewer_app.jsx",
        "./static/src/javascripts/components/side_quiz.jsx",
        "./static/src/javascripts/lib/highlight.js",
        "./static/src/javascripts/lib/verb_analysis.js",
    ],
    darkMode: false, // or 'media' or 'class'
    theme: {},
    variants: {},
    plugins: [],
};
